### ISSUE TITLE
Catmull Curve Implementation

### ISSUE THREAD

**Issue by NotMichaelChen** [llllllllll/slider#20]
If anyone's interested in implementing catmull curves for completion's sake, here's a webpage describing how to interpolate them: [http://cubic.org/docs/hermite.htm](http://cubic.org/docs/hermite.htm) (under the section "Catmull-Rom Splines")

Some additional notes on how they're implemented in osu:
- osu calculates one curve for each pair of adjacent points in a slider (so for example osu calculates 3 curves for a slider with 4 points)
- The tangent variable for the first and last points in the slider are calculated assuming that the previous/next points are repeated. For example, the tangent variable for the first point is calculated as T_1 = 0.5 * (P_1 - P_2)

**Comment by llllllllll** [comment]
Thanks for the resources, this is a big help! We haven't gotten around to this, mostly because these are only used in older beatmaps and most of the developers' time has been focused on handling more recent maps.

If you want to try to implement this I would love to walk you through how the curve code works now. If not, thanks for helping the next person that wants to tackle this!

**Comment by NotMichaelChen** [comment]
Totally agree with catmull curves being very low priority (I don't think any ranked catch-the-beat maps make use of catmull curves). Still, it's an interesting bit of functionality to implement.

Unfortunately I just started getting back into coding my osu tools and I have a lot of garbage to clean up in my own libraries. I guess this can be left as an exercise for the reader :P

**Comment by tybug** [comment]
I know this is an old issue but thank you very much for that hermite curve link @NotMichaelChen, was the main source I used to understand catmull sliders
